config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    root to: 'admins#index', as: :authenticated_admin_root
  end
  get 'admins/index', as: 'admins_index'
  
  resources :admins do 
    member do
      post :approve_account
      post :decline_account
    end
  end
  get '/pending', to: 'admins#pending'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: "users/passwords" 
  }

  resources :banks 
  resources :accounts 
  resources :transactions 

  root to: 'users#index'
  get '/get_users_by_bank', to: 'transactions#get_users_by_bank'


  resources :users do 
    member do
      post :create_account_request
      get :approve
      get :decline
    end
  end

      
end

app/views/admins/index.html.erb
<div class="moving-text" style="padding: 22px">
<div class="text-center p-3"> 
  <h1 class="bordered-div" style="color: black"><strong>Welcome to Admin Dashboard </strong></h1> </div>
  <br>
  <div style="color:black">
    <h2><strong class="bordered-div">Users Available</strong></h2>

      <% @users.where(approved: true).reverse.each do |user| %>
        <% unless user.admin? %>
          <a href="<%= user_path(user) %>" style="text-decoration: none;">  <br>
           <h3> <strong style="color:blue"><%= user.first_name %> <%= user.last_name%></strong></h3> 
          </a>
          <p> <strong><%= user.email %></strong></p>
          <% if user.pending_accounts.any? %> 
            <div>
              <% user.pending_accounts.reverse.each do |account| %>
                <p><strong>Account Request:</strong> <%= account.bank.bank_name %></p> 
                <%= form_with url: approve_account_admin_path(account), method: :post do |f| %>
                  <%= f.submit 'Approve', class: 'btn btn-success' %>
                <% end %>
                <br>
                <%= form_with url: decline_account_admin_path(account), method: :post do |f| %>
                  <%= f.submit 'Decline', class: 'btn btn-danger' %>
                <% end %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <br>
    <br>
</div>
<br>
<br>

app/views/admins/pending.html.erb
<div class="moving-text" style="padding: 22px">
<h2><strong class="bordered-div" style='color:black'> Users waiting for Approval </strong></h2>
<br>
  <% @users.where(approved: false).reverse.each do |user| %>
    <div>
    <br>
     <p> <strong> <%= user.email %> </strong>
   <%= user.first_name %> <%= user.last_name%></p> 

    <%= link_to 'Approve', approve_user_path(user), method: :patch, class: 'btn btn-success'%>
      <%= link_to 'Decline', decline_user_path(user), method: :patch, class: 'btn btn-danger' %>
  <% end %>
</div>
</div>
<br>
<br>