config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    root to: 'admins#index', as: :authenticated_admin_root
  end
  get 'admins/index', as: 'admins_index'
  
  resources :admins do 
    member do
      post :approve_account
      post :decline_account
    end
  end
  get '/pending', to: 'admins#pending'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: "users/passwords" 
  }

  resources :banks 
  resources :accounts 
  resources :transactions 

  root to: 'users#index'
  get '/get_users_by_bank', to: 'transactions#get_users_by_bank'


  resources :users do 
    member do
      post :create_account_request
      get :approve
      get :decline
    end
  end

      
end

app/models/bank.rb
class Bank < ApplicationRecord

    validates :bank_name, presence: true, uniqueness: true

    has_many :accounts, dependent: :destroy
    has_many :users, through: :accounts

end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :require_admin, except: [:index, :show]
  before_action :to_find_bank, only: [:show, :edit, :update, :destroy]
  
  def index
    @banks = Bank.all
  end
  def show
  rescue ActiveRecord::RecordNotFound
    redirect_to banks_path, alert: "Bank not found"
  end

  def new
    @bank = Bank.new
  end

  def create
    @bank = Bank.new(bank_params)

    if @bank.save
      redirect_to @bank
    else
      render :new, status: :unprocessable_entity
    end
  end
  def edit
  rescue ActiveRecord::RecordNotFound
    redirect_to banks_path, alert: "Bank not found"
  end
  def update
    if @bank.update(bank_params)
      redirect_to @bank, notice: "Bank updated successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bank.destroy
    redirect_to banks_path, notice: 'Bank was successfully destroyed.'
  end

  def to_find_bank
    @bank = Bank.find(params[:id])
  end

  private

  def bank_params
    params.require(:bank).permit(:bank_name)
  end
  def require_admin
    unless current_user&.admin?
      redirect_to root_path, alert: "You are not authorized to perform this action."
    end
  end
  
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/views/banks/_form.html.erb
<%= form_with(model: @bank, url: banks_path, local: true) do |form| %>
  <% if @bank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank.errors.count, "error") %> You are providing a wrong bank details: </h2>

      <ul>
        <% @bank.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div style="color:black">
  <div class="field">
    <%= form.label :bank_name %>
    <%= form.text_field :bank_name %>
  </div> </div>
  <br>
  <div class="actions">
    <%= form.submit  "Create Account", class: "btn btn-primary"%>
    <%= link_to 'Back', banks_path, class: 'btn btn-secondary'%>
  </div>
<% end %>

app/views/banks/edit.html.erb
<div class="moving-text" style="padding: 22px">
<h1 class="bordered-div" style="color: black"> Edit Bank </h1> 
<br>
<%= form_for @bank do |f| %>
<div style="color:black">
  <%= f.label :bank_name %>
  <%= f.text_field :bank_name %> </div>
  <br>
  <p>
  <%= f.submit 'Update', class: 'btn btn-primary' %>
  <%= link_to 'Back', banks_path, class: 'btn btn-secondary'%> </p>
<% end %>
<br>
<%= link_to 'Delete Bank', @bank, method: :delete,data: {turbo_method: :delete,  turbo_confirm: "Are you sure"} , class: 'btn btn-danger' %>

</div>

app/views/banks/index.html.erb
<div class="moving-text" style="padding: 22px">
<div class="text-center p-3"> 
  <h1 class="bordered-div" style="color: black">List of all Banks</h1> </div>
  <div>
      <ul>
        <% @banks.each do |bank| %>
          <li><h3> 
          <a href="<%= bank_path(bank) %>"style="text-decoration:none; color:blue">
          <%= bank.bank_name %>
          </a>
           </h3></li>
        <% end %>
      </ul>
     <%= link_to 'Back', root_path, class: 'btn btn-secondary' %> </p>
    </div>

</div>

app/views/banks/new.html.erb
<div class="moving-text" style="padding: 22px">
<div class="text-center p-3"> 
<h1 class="bordered-div" style="color: black">Add New Bank Here</h1> </div>

<%= render 'form' %>

</div>

app/views/banks/show.html.erb
<div  class="moving-text"  style="padding: 22px">
<div class="text-center p-3">
  <h1 class="bordered-div" style="color:black"><%= @bank.bank_name %></h1> </div>
  
  <% unless current_user.admin? %>
    <h3><strong style="color:black">Accounts Details</strong></h3>
    <% if @bank.accounts.where(user_id: current_user.id).any? %>
      <% @bank.accounts.where(user_id: current_user.id).each do |account| %>
        <div style="color: black">
          <p><strong>User:</strong> <%= current_user.first_name %> <%= current_user.last_name %> </p>
          <p><strong>Email:</strong> <%= current_user.email %></p>
          <p><strong>Account Number:</strong> <%= account.account_no %></p>
          <p><strong>Balance:</strong> <%= account.balance %></p>
        </div>
      <% end %>
    <% else %>
      <p style="color:black">No accounts found.</p>
    <% end %>
  <% end %>

  <% if current_user.admin? %>
    <% users = @bank.users %>
    <% if users.any? %>
      <ul>
        <% users.each do |user| %>
          <li> <a href="<%= user_path(user) %>" style="text-decoration: none;color:blue"><strong>User:</strong> <%= user.email %> </a></li>
          <% user_accounts = user.accounts.where(bank_id: @bank.id) %>
          <% if user_accounts.any? %>
            <ul style="color:black">
              <% user_accounts.each do |account| %>
                <li >
                  <strong>Account Number:</strong>
                  <%= account.account_no %><br>
                </li>
                <li> <strong>Balance:</strong>
                  <%= account.balance %> </li>
              <% end %>
            </ul>
          <% else %>
            <li>No accounts found for this user.</li>
          <% end %>
        <% end %>
      </ul>
    <% else %>
      <p>No users found for this bank.</p>
    <% end %>
   <p>
    <%= link_to 'Edit this bank', edit_bank_path(@bank), class: 'btn btn-primary' %>
  <% end %>
  <%= link_to 'Back', banks_path, class: 'btn btn-secondary' %> </p>

</div>