config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    root to: 'admins#index', as: :authenticated_admin_root
  end
  get 'admins/index', as: 'admins_index'
  
  resources :admins do 
    member do
      post :approve_account
      post :decline_account
    end
  end
  get '/pending', to: 'admins#pending'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: "users/passwords" 
  }

  resources :banks 
  resources :accounts 
  resources :transactions 

  root to: 'users#index'
  get '/get_users_by_bank', to: 'transactions#get_users_by_bank'


  resources :users do 
    member do
      post :create_account_request
      get :approve
      get :decline
    end
  end

      
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name,:last_name,:email,:date_of_birth,:phone,:gender, presence: true
  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :phone, uniqueness: true 
  
  has_many :pending_accounts, -> { where(status: :pending) }, class_name: 'Account'
  has_one_attached :header_image

  has_many :accounts , dependent: :destroy
  
 
  def active_for_authentication?
       super && self.approved?
  end                           
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params
   def new
    @user = User.new
  end

# POST /resource
def create
    @user = User.new(user_params)
  if @user.save
    UserMailer.sample(User.new(email: 'hafeezmalik@isoftstudios.com')).deliver
    redirect_to root_path, notice: 'User created successfully.' 
  else
    render :new
  end
end


  
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end


  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :date_of_birth, :phone, :gender])
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private
  def after_inactive_sign_up_path_for(resource)
    if resource.is_a?(User)
      flash[:notice] = "Please wait until admin approves your account."
      root_path
    else
      super
    end
  end
  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name, :date_of_birth, :phone, :gender, :header_image)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
   # self.resource = resource_class.new(sign_in_params)
   # clean_up_passwords(resource)
   # yield resource if block_given?
   # respond_with(resource, serialize_options(resource))
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end
  #def create
   # user = User.find_by(email: params[:user][:email].downcase)
  
    #if user&.valid_password?(params[:user][:password])
    #  if user.approved?
     #   sign_in(user)
      #  redirect_to root_path, notice: "Logged in successfully."
      #else
      #  flash.now[:alert] = "Your account is awaiting admin approval. Please wait for approval."
      #  render 'new'
     # end
   # else
    #  flash.now[:alert] = "Invalid email or password."
     # render 'new'
   # end
 # end
  
  


  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :to_find_the_user, only: [:show, :edit, :destroy, :create_account_request]
  

  def index
    if user_signed_in?
      @user = current_user
      @banks = Bank.joins(:accounts).where(accounts: { user_id: @user.id, status: 1 }).distinct
      @account_count = @user.accounts.where(status: 1).count
      @accounts = @user.accounts.where(status: 1)

    end
  end

  def show
    if current_user.admin? && params[:id].to_i != current_user.id
    else
      @user = current_user
    end
    rescue ActiveRecord::RecordNotFound
    redirect_to user_path(current_user), alert: "User not found"
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: 'User created successfully.' 
    else
      render :new
    end
  end

  def edit
    if current_user.admin? && params[:id].to_i != current_user.id
    else
      @user = current_user
    end
  end

  def update
    @user = current_user
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Profile updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: 'User was successfully deleted.'
  end
  def create_account_request
    @bank = Bank.find(params[:id])
    @account = @bank.accounts.build(user: @user, status: :pending)

    if @account.save
      redirect_to user_path(@user), notice: 'Account creation request sent for approval.'
    else
      redirect_to bank_path(@bank), alert: 'Account creation request failed.'
    end
  end
  def to_find_the_user
    @user = User.find(params[:id])
  end
  def approve
  @user = User.find(params[:id])
  @user.update(approved: true)

  redirect_to pending_path, notice: 'User approved successfully.'
  end

  def decline
  @user = User.find(params[:id])
  @user.destroy
  redirect_to pending_path, notice: 'User declined successfully.'
  end
  def active_for_authentication?
  super && (approved? || admin?)
  end
  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :date_of_birth, :phone, :gender, :header_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_userform.html.erb
<%= form_for @user, url: user_path(@user), method: :patch, html: { multipart: true } do |f| %>
   <div style="padding: 13px; color:black" >
   <div class="field">
    <%= f.label :first_name %> <br>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %> <br>
    <%= f.text_field :last_name %>
  </div>
   <br>
  <div class="field">
    <%= f.label :date_of_birth %>
    <%= f.date_field :date_of_birth %>
  </div><br>
  <div class="field">
    <%= f.label :phone %> 
    <%= f.text_field :phone %>
  </div><br>
  <div class="field">
    <%= f.label :gender %>
    <%= f.select :gender, ["Male", "Female", "Other"] %>
  </div><br>
  <div class="field">
   <%= f.file_field :header_image %>
 </div>

  
  <br>
  <%= f.submit "Update", class: "btn btn-primary" %> 
   <%= link_to "Back", root_path, class: "btn btn-secondary" %>
  </div>
  <% end %>

app/views/users/edit.html.erb
<div class="moving-text" style= "padding: 13px;">
<div class="text-center p-3"> 

<h1 class="bordered-div" style="color: black">Edit Profile</h1> </div>
<%= render 'userform' %>
<br>

<% if current_user.admin? && @user != current_user %>
  <%= link_to 'Delete User', user_path(@user), data: { turbo_method: :delete, turbo_confirm: 'Are you sure' }, class: 'btn btn-danger' %>
<% end %>

</div>

app/views/users/index.html.erb
<div class="container-fluid">
  <div class="moving-text" style="padding: 22px; color: black;">
    <% if user_signed_in? %>
    


      <div class="text-center p-3">
        <h1 class="bordered-div" style="color: black;">Welcome to Banking App (All banks in one app)</h1>
      </div>
      <br>
      <h1><strong>Number of Accounts:</strong> <%= @account_count %></h1>
      <br>
      <% if @accounts.present? %>
        <div>
          <h1><strong>Your Account Details:</strong></h1>
          <table class="table table-bordered table-striped">
            <thead>
              <tr style="background-color: #f0ad4e; color: white;">
                <th>Bank</th>
                <th>Account Number</th>
                <th>Balance</th>
              </tr>
            </thead>
            <tbody>
              <% @accounts.each do |account| %>
                <tr style="color: black;">
                  <td><%= account.bank.bank_name %></td>
                  <td><%= account.account_no %></td>
                  <td class="balance-cell"><strong><%= account.balance %></strong></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
       
      <% else %>
        <p style="color: black;">No accounts found.</p>
      <% end %>
    <% else %>
      <div class="bordered-div" >
      <h1 class="moving-text" style="color: black">Welcome to Banking App (All banks in one app)</h1>
      <p class="moving-text" style="color: black">
      <strong>
        Manage your finances with ease.
        In this rapidly evolving digital era, the world of banking has undergone a profound transformation. Gone are the days of long queues, 
        complex paperwork, and limited accessibility.
        With the advent of innovative technologies, banking has become more streamlined, efficient, and customer-centric.
        One such groundbreaking innovation is the ultimate banking app, a game-changer in the financial industry.
        This blog aims to explore the features and benefits of this revolutionary banking app, highlighting how it 
        facilitates users and enhances their banking experience.
        <br>The ultimate banking app represents a significant leap forward in the world of banking, 
        revolutionizing how users interact with their finances. <br>With its seamless account management,
        secure transactions, personalized insights, exceptional customer support, 
        robust security features, and integration with third-party services, 
        this app is a game-changer in the industry. By placing the power of banking in users' 
        hands, it empowers individuals to take control of their financial well-being and achieve 
        their financial goals. As we embrace the digital future, the ultimate banking app stands at the forefront, 
        redefining banking convenience and setting new standards for customer-centric financial services.</strong><br>
        </p> <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
      <%= link_to "Log In", new_user_session_path, class: "btn btn-secondary" %></div>
      <div>
      <br><br><br>
    
      <h1> Contact us:</h1>
      <p>Phone: <strong>(042) 35312424 </strong> </p>
      <p>Cell: <strong> +92 3244282516 </strong> </p>
      <p>Email: <strong> faizanshk20@ucp.edu.pk </strong> </p>
      </div>
      <div>
      <%= link_to 'https://www.facebook.com/faizansh1may', target: :_blank, style:'text-decoration:none;' do %>
      <%= image_tag 'fb.png', alt: "fblogo" %> <% end %>
       <%= link_to 'https://www.instagram.com/faizan__sheikh__', target: :_blank, style:'text-decoration:none;' do %>
       <%= image_tag 'Ig.png', alt: "Iglogo" %>  <% end %>
      <%= link_to 'https://www.linkedin.com/in/faizansheikh5', target: :_blank, style:'text-decoration:none;' do %>
        <%= image_tag 'Ld.png', alt: "Ldlogo" %> <% end %>
       <%= link_to 'https://twitter.com/faizanshk20', target: :_blank do %>
       <%= image_tag 'twitter.png', alt: "Twitter" %> </a> <% end %>
      </div>
    <% end %>
<br> <br> <br>
</div>

app/views/users/show.html.erb
<div class="moving-text" style="padding: 22px">
  <div class="text-center p-3">
  <h1 class="bordered-div" style="color: black">User Details</h1> </div>

  <div style="color:black">
    <p><strong>First Name:</strong> <%= @user.first_name %></p>
    <p><strong>Last Name:</strong> <%= @user.last_name %></p>
    <p><strong>Email:</strong> <%= @user.email %></p>
    <p><strong>Gender:</strong> <%= @user.gender %></p>
    <p><strong>DOB:</strong> <%= @user.date_of_birth %></p>
    <p><strong>Phone:</strong> <%= @user.phone %></p>
     <p>
    <%if @user.header_image.attached?%>
  <%= image_tag @user.header_image, class: "img-fluid", style: "max-width: 250px; height: auto;" %>
  <% end %>
 </p>

  </div>
  <div>
  <% if current_user.admin? && @user != current_user %>
    <% if @user.accounts.any? %>
      <h2><strong>Accounts</strong></h2>
      <ul>
        <% @user.accounts.each do |account| %>
        <a href="<%= account_path(account) %>" style="text-decoration: none; color:blue">
          <li><strong><%= "#{account.bank.bank_name} Account" %></strong></li><br>
          </a>
       
        <% end %>
      </ul>
    <% end %>
  <% end %>
  <p>
  <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-primary" %> 
  <%= link_to "Back", current_user.admin? ? admins_index_path : root_path, class: "btn btn-secondary" %> 
  </p>
  <br><br>
</div>