config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    root to: 'admins#index', as: :authenticated_admin_root
  end
  get 'admins/index', as: 'admins_index'
  
  resources :admins do 
    member do
      post :approve_account
      post :decline_account
    end
  end
  get '/pending', to: 'admins#pending'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: "users/passwords" 
  }

  resources :banks 
  resources :accounts 
  resources :transactions 

  root to: 'users#index'
  get '/get_users_by_bank', to: 'transactions#get_users_by_bank'


  resources :users do 
    member do
      post :create_account_request
      get :approve
      get :decline
    end
  end

      
end

app/views/shared/_footer.html.erb
<footer class="footer">
 
  <div class="text-center p-3 bg-grey" style="background-color: rgba(0, 0, 0, 0.2); color: white;">
   All right reserved to Copyright © 2023. 
    <a style="color:blue" href="<%= root_path %>">support@koksalbanking.com</a>
  </div>
 
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgba(0, 0, 0, 0.2);">
  <div class="container-fluid">
    <%= link_to root_path do %>
    <%= image_tag 'banklogo.png', alt: "Logo", width: "50", height: "50", style: "margin-left: 10px;" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
        <%= link_to "Home", root_path, class: "nav-link", style: "margin-left: 25px;"%>
          <%= link_to "Banks", banks_path, class: "nav-link" %>
          <% unless current_user.admin? %>
            <%= link_to "Create new Account", new_account_path, data: { controller: 'user-modal'}  ,class: "nav-link" %>
            <%= link_to "Make a Transaction", new_transaction_path, class: "nav-link" %>
          <% else %>
            <%= link_to "Pending Requests", pending_path, class: "nav-link" %>
          <% end %>
        </div>
        <div class="navbar-nav ms-auto">
        <a href="<%= user_path(current_user) %>">
        <%= image_tag current_user.header_image, class: "img-fluid rounded-circle", 
        style: "width: 40px; height: 40px; border-radius: 100px;" if current_user&.header_image.attached? %> </a>
          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.email %> 
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
            <% if current_user.admin? %>
            <%= link_to "Create New Bank", new_bank_path, class: "dropdown-item" %>
            <% end %>
            <% unless current_user.admin?%>
              <%= link_to "Accounts", accounts_path, class: "dropdown-item" %>
              <%= link_to "Transactions", transactions_path, class: "dropdown-item"%>
              <% end %>
              <li><hr class="dropdown-divider"></li>
              <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</nav>